<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="">
<meta name="author" content="">

<?= \Module\HttpFoundation\Actions::htmlHeadTitle('Poirot Framework') ?>

<link href="<?= \Module\Foundation\Actions::path('theme') ?>/css/bootstrap.min.css" rel="stylesheet">
<link href="<?= \Module\Foundation\Actions::path('theme') ?>/css/font-awesome.min.css" rel="stylesheet">
<link href="<?= \Module\Foundation\Actions::path('theme') ?>/css/prettyPhoto.css" rel="stylesheet">
<link href="<?= \Module\Foundation\Actions::path('theme') ?>/css/animate.css" rel="stylesheet">
<link href="<?= \Module\Foundation\Actions::path('theme') ?>/css/main.css" rel="stylesheet">
<!--[if lt IE 9]>
<script src="<?= \Module\Foundation\Actions::path('theme') ?>/js/html5shiv.js"></script>
<script src="<?= \Module\Foundation\Actions::path('theme') ?>/js/respond.min.js"></script>
<![endif]-->
<link rel="shortcut icon" href="<?= \Module\Foundation\Actions::path('theme') ?>/images/ico/favicon.ico">
<link rel="apple-touch-icon-precomposed" sizes="144x144" href="<?= \Module\Foundation\Actions::path('theme') ?>/images/ico/apple-touch-icon-144-precomposed.png">
<link rel="apple-touch-icon-precomposed" sizes="114x114" href="<?= \Module\Foundation\Actions::path('theme') ?>/images/ico/apple-touch-icon-114-precomposed.png">
<link rel="apple-touch-icon-precomposed" sizes="72x72" href="<?= \Module\Foundation\Actions::path('theme') ?>/images/ico/apple-touch-icon-72-precomposed.png">
<link rel="apple-touch-icon-precomposed" href="<?= \Module\Foundation\Actions::path('theme') ?>/images/ico/apple-touch-icon-57-precomposed.png">

<?= \Module\HttpFoundation\Actions::htmlLink() ?>
