<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="">
<meta name="author" content="">

<?= \Module\HttpFoundation\Actions::htmlHeadTitle('Poirot Framework') ?>

<?php \Module\HttpFoundation\Actions::htmlLink()
    ->group()
    ->withPathPrefix(\Module\Foundation\Actions::path('theme'))
    ->withOffsetIota(-100)
    ->attachFile('css/bootstrap.min.css')
    ->attachFile('css/font-awesome.min.css')
    ->attachFile('css/prettyPhoto.css')
    ->attachFile('css/animate.css')
    ->attachFile('css/main.css')
    // Icons
    ->attachFile('images/ico/favicon.ico', null, [], 'shortcut icon')
    ->attachFile('images/ico/apple-touch-icon-144-precomposed.png', null, ['sizes'=>'144x144'], 'apple-touch-icon-precomposed')
    ->attachFile('images/ico/apple-touch-icon-114-precomposed.png', null, ['sizes'=>'114x114'], 'apple-touch-icon-precomposed')
    ->attachFile('images/ico/apple-touch-icon-72-precomposed.png', null, ['sizes'=>'72x72'], 'apple-touch-icon-precomposed')
    ->attachFile('images/ico/apple-touch-icon-57-precomposed.png', null, [], 'apple-touch-icon-precomposed')
;

print \Module\HttpFoundation\Actions::htmlLink();

print \Module\HttpFoundation\Actions::htmlScript('head')
    ->group()
    ->withPathPrefix(\Module\Foundation\Actions::path('theme'))
    ->withOffsetIota(-100)
        ->attachFile('js/html5shiv.js', null, ['conditional' => 'lt IE 9'])
        ->attachFile('js/respond.min.js', null, ['conditional' => 'lt IE 9'])
;
