<!DOCTYPE html>
<html lang="en">
<head>
    <?= $this->capture('inc.header.phtml') ?>
</head>
<body>
<header class="navbar navbar-inverse navbar-fixed-top wet-asphalt" role="banner">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<?= \Module\HttpFoundation\Actions::url('main/home') ?>">
                <h4>Poirot Framework</h4>
            </a>
        </div>

        <?= $this->capture('inc.navigation-menu.phtml') ?>

    </div>
</header>

<?= $content; ?>

<?= $this->capture('inc.footer.phtml') ?>
</body>
</html>
